package pathx.ui;


public enum pathXTileState
{
    INVISIBLE_STATE,
    VISIBLE_STATE,
    SELECTED_STATE,
    MOUSE_OVER_STATE,
    AVAILABLE_STATE,
    UNAVAILABLE_STATE,
    COMPLETED_STATE,
    WIN_STATE,
    LOSE_STATE
    
}